#ARG ARCH='x86_64'
#ARG RHEL_VERSION='9.3'
#ARG KERNEL_VERSION='5.14.0-362.13.1'
#ARG BASE_DIGEST=''
FROM quay.io/ebelarte/driver-toolkit:5.14.0-362.13.1.el9_3 as builder

ARG ARCH='x86_64'
ARG DRIVER_VERSION='535.104.05'
ARG DRIVER_EPOCH='1'
ARG KERNEL_VERSION='5.14.0-362.13.1.el9_3'
ARG RHEL_VERSION='9.3'
ARG KERNEL_SOURCES='/usr/src/kernels/${KERNEL_VERSION}.${ARCH}'
ARG KERNEL_OUTPUT='/usr/src/kernels/${KERNEL_VERSION}.${ARCH}'

WORKDIR /home/builder

RUN export KVER=$(echo ${KERNEL_VERSION} | cut -d '-' -f 1) \
        KREL=$(echo ${KERNEL_VERSION} | cut -d '-' -f 2 | sed 's/\.el._.$//') \
        KDIST=$(echo ${KERNEL_VERSION} | cut -d '-' -f 2 | sed 's/^.*\(\.el._.\)$/\1/') \
        DRIVER_STREAM=$(echo ${DRIVER_VERSION} | cut -d '.' -f 1) \
        KSOURCES=$(echo ${KERNEL_VERSION}.${ARCH}) && \
        git clone -b ${DRIVER_VERSION}  https://github.com/NVIDIA/open-gpu-kernel-modules.git && \
        cd open-gpu-kernel-modules && \
        make SYSSRC=${KERNEL_SOURCES} SYSOUT=${KERNEL_OUTPUT} modules

FROM archlinux:latest as buildsdk
MAINTAINER Enrique Belarte Luque <ebelarte@redhat.com>
# Update the repositories
RUN pacman -Syy
# Install AWS SDK C++ and other needed packages
RUN pacman -Sy --noconfirm aws-sdk-cpp git base-devel aws-sdk-cpp libp11 && \
    find /var/cache/pacman/ -type f -delete
# Clone PKCS11 implementation to use AWS KMS as backend
RUN git clone https://github.com/JackOfMostTrades/aws-kms-pkcs11.git && \
    cd aws-kms-pkcs11 && \
    make install

FROM archlinux:latest
# Set enviroment variables for AWS auth
#ENV AWS_ACCESS_KEY_ID=your_access_key_id
#ENV AWS_SECRET_ACCESS_KEY=your_secret_access_key
ENV AWS_DEFAULT_REGION=eu-west-3
#ENV AWS_KMS_TOKEN=xxxxxxx-xxxx-xxxxxx-xxxxx
# Copy the library from previous build step
COPY --from=buildsdk /usr/lib/pkcs11/aws_kms_pkcs11.so /usr/lib/pkcs11/aws_kms_pkcs11.so
# Copy configuration files for aws-kms-pkcs11 library
COPY config.json x509.genkey openssl-pkcs11.conf /etc/aws-kms-pkcs11/
# Copy aws-sdk needed libraries
COPY --from=buildsdk /usr/lib/libaws* /usr/lib/libs2n.so /usr/lib/
# Copy shell script to update config
COPY configure_pkcs.sh /bin/
# Update the repositories
RUN pacman -Syy
# Install linux-headers to get sign-file script, AWS client and pkcs11 lib
RUN pacman -Sy --noconfirm linux-headers aws-cli libp11 && \
    find /var/cache/pacman/ -type f -delete

